version: "3"
services:
  promptree-db:
    image: amd64/postgres:15.1
    container_name: promptree-db
    restart: always
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_DB: "promptree"
      POSTGRES_USER: "leniolabs"
      POSTGRES_PASSWORD: "leniolabs"
    ports:
      - "5432:5432"
    expose:
      - "5432"


      